[package]
name = "neon_term"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
device_query = "4.0.1"
noise = "0.9.0"
rand = "0.9.0"

[profile.release]
codegen-units = 1
lto = "fat"

[build]
rustflags = ["-C","target-cpu=native"]
